# Generated by Django 3.0.4 on 2020-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200310_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='end_No',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_No',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='check_box',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='discrepency',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
